CREATE TABLE IF NOT EXISTS llm_requests (
  id TEXT PRIMARY KEY,
  "requestId" TEXT NOT NULL,
  "configId" TEXT,
  "variantId" TEXT,
  "environmentId" TEXT,
  "providerConfigId" TEXT,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "cachedTokens" INTEGER NOT NULL DEFAULT 0,
  "cacheCreationTokens" INTEGER NOT NULL DEFAULT 0,
  cost INTEGER NOT NULL DEFAULT 0,
  "cacheSavings" INTEGER NOT NULL DEFAULT 0,
  "inputCost" INTEGER NOT NULL DEFAULT 0,
  "outputCost" INTEGER NOT NULL DEFAULT 0,
  endpoint TEXT NOT NULL,
  "statusCode" INTEGER NOT NULL,
  "latencyMs" INTEGER NOT NULL DEFAULT 0,
  "isStreaming" INTEGER NOT NULL DEFAULT 0,
  "userId" TEXT,
  tags TEXT NOT NULL DEFAULT '{}',
  "guardrailResults" TEXT,
  "traceId" TEXT,
  "spanId" TEXT,
  "parentSpanId" TEXT,
  "sessionId" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now')),
  "updatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS span_events (
  id TEXT PRIMARY KEY,
  "traceId" TEXT NOT NULL,
  "spanId" TEXT NOT NULL,
  name TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  attributes TEXT NOT NULL DEFAULT '{}',
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS spans (
  id TEXT PRIMARY KEY,
  "traceId" TEXT NOT NULL,
  "spanId" TEXT NOT NULL UNIQUE,
  "parentSpanId" TEXT,
  name TEXT NOT NULL,
  kind INTEGER NOT NULL DEFAULT 1,
  status INTEGER NOT NULL DEFAULT 0,
  "statusMessage" TEXT,
  "startTime" TEXT NOT NULL,
  "endTime" TEXT,
  "durationMs" INTEGER,
  provider TEXT,
  model TEXT,
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  cost INTEGER NOT NULL DEFAULT 0,
  "configId" TEXT,
  "variantId" TEXT,
  "environmentId" TEXT,
  "providerConfigId" TEXT,
  "requestId" TEXT,
  source TEXT NOT NULL DEFAULT 'gateway',
  input TEXT,
  output TEXT,
  attributes TEXT NOT NULL DEFAULT '{}',
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now')),
  "updatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS traces (
  id TEXT PRIMARY KEY,
  "traceId" TEXT NOT NULL UNIQUE,
  name TEXT,
  "sessionId" TEXT,
  "userId" TEXT,
  status TEXT NOT NULL DEFAULT 'unset',
  "startTime" TEXT NOT NULL,
  "endTime" TEXT,
  "durationMs" INTEGER,
  "spanCount" INTEGER NOT NULL DEFAULT 0,
  "totalInputTokens" INTEGER NOT NULL DEFAULT 0,
  "totalOutputTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "totalCost" INTEGER NOT NULL DEFAULT 0,
  tags TEXT NOT NULL DEFAULT '{}',
  metadata TEXT NOT NULL DEFAULT '{}',
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now')),
  "updatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);
