CREATE TABLE llm_requests (
  "id" UUID PRIMARY KEY,
  "requestId" UUID NOT NULL,
  "configId" UUID,
  "variantId" UUID,
  "environmentId" UUID,
  "providerConfigId" UUID,
  "provider" VARCHAR(255) NOT NULL,
  "model" VARCHAR(255) NOT NULL,
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "cachedTokens" INTEGER NOT NULL DEFAULT 0,
  "cacheCreationTokens" INTEGER NOT NULL DEFAULT 0,
  "cost" INTEGER NOT NULL DEFAULT 0,
  "cacheSavings" INTEGER NOT NULL DEFAULT 0,
  "inputCost" INTEGER NOT NULL DEFAULT 0,
  "outputCost" INTEGER NOT NULL DEFAULT 0,
  "endpoint" VARCHAR(255) NOT NULL,
  "statusCode" INTEGER NOT NULL,
  "latencyMs" INTEGER NOT NULL DEFAULT 0,
  "isStreaming" BOOLEAN NOT NULL DEFAULT false,
  "userId" VARCHAR(255),
  "tags" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "guardrailResults" JSONB,
  "traceId" VARCHAR(255),
  "spanId" VARCHAR(255),
  "parentSpanId" VARCHAR(255),
  "sessionId" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
