CREATE TABLE spans (
  "id" UUID PRIMARY KEY,
  "traceId" VARCHAR(255) NOT NULL,
  "spanId" VARCHAR(255) NOT NULL UNIQUE,
  "parentSpanId" VARCHAR(255),
  "name" VARCHAR(255) NOT NULL,
  "kind" INTEGER NOT NULL DEFAULT 1,
  "status" INTEGER NOT NULL DEFAULT 0,
  "statusMessage" TEXT,
  "startTime" TIMESTAMP NOT NULL,
  "endTime" TIMESTAMP,
  "durationMs" INTEGER,
  "provider" VARCHAR(255),
  "model" VARCHAR(255),
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "cost" INTEGER NOT NULL DEFAULT 0,
  "configId" UUID,
  "variantId" UUID,
  "environmentId" UUID,
  "providerConfigId" UUID,
  "requestId" UUID,
  "source" VARCHAR(50) NOT NULL DEFAULT 'gateway',
  "input" JSONB,
  "output" JSONB,
  "attributes" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
