CREATE TABLE llm_requests (
  "id" TEXT PRIMARY KEY,
  "requestId" TEXT NOT NULL,
  "configId" TEXT,
  "variantId" TEXT,
  "environmentId" TEXT,
  "providerConfigId" TEXT,
  "provider" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "cachedTokens" INTEGER NOT NULL DEFAULT 0,
  "cacheCreationTokens" INTEGER NOT NULL DEFAULT 0,
  "cost" INTEGER NOT NULL DEFAULT 0,
  "cacheSavings" INTEGER NOT NULL DEFAULT 0,
  "inputCost" INTEGER NOT NULL DEFAULT 0,
  "outputCost" INTEGER NOT NULL DEFAULT 0,
  "endpoint" TEXT NOT NULL,
  "statusCode" INTEGER NOT NULL,
  "latencyMs" INTEGER NOT NULL DEFAULT 0,
  "isStreaming" INTEGER NOT NULL DEFAULT 0,
  "userId" TEXT,
  "tags" TEXT NOT NULL DEFAULT '{}',
  "guardrailResults" TEXT,
  "traceId" TEXT,
  "spanId" TEXT,
  "parentSpanId" TEXT,
  "sessionId" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now')),
  "updatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);
