CREATE TABLE spans (
  "id" TEXT PRIMARY KEY,
  "traceId" TEXT NOT NULL,
  "spanId" TEXT NOT NULL UNIQUE,
  "parentSpanId" TEXT,
  "name" TEXT NOT NULL,
  "kind" INTEGER NOT NULL DEFAULT 1,
  "status" INTEGER NOT NULL DEFAULT 0,
  "statusMessage" TEXT,
  "startTime" TEXT NOT NULL,
  "endTime" TEXT,
  "durationMs" INTEGER,
  "provider" TEXT,
  "model" TEXT,
  "promptTokens" INTEGER NOT NULL DEFAULT 0,
  "completionTokens" INTEGER NOT NULL DEFAULT 0,
  "totalTokens" INTEGER NOT NULL DEFAULT 0,
  "cost" INTEGER NOT NULL DEFAULT 0,
  "configId" TEXT,
  "variantId" TEXT,
  "environmentId" TEXT,
  "providerConfigId" TEXT,
  "requestId" TEXT,
  "source" TEXT NOT NULL DEFAULT 'gateway',
  "input" TEXT,
  "output" TEXT,
  "attributes" TEXT NOT NULL DEFAULT '{}',
  "createdAt" TEXT NOT NULL DEFAULT (datetime('now')),
  "updatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);
